apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svc-gateway
  namespace: argocd
spec:
  project: services
  source:
    repoURL: https://github.com/2025-demo-01/svc-gateway
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
