apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prod
spec:
  project: platform
  source:
    repoURL: https://github.com/2025-demo-01/observability-stack.git
    targetRevision: v0.9.0
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
