apiVersion: v1
kind: Secret
metadata:
  name: trading-api
  namespace: trading
type: Opaque
stringData:
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    ...
    -----END PUBLIC KEY-----
  REDIS_URL: redis://redis.trading.svc.cluster.local:6379
