apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "90" }
spec:
  project: platform
  source:
    repoURL: 'https://github.com/2025-demo-01/observability-stack'
    targetRevision: main
    path: k8s
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: { prune: true, selfHeal: true }
