apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-pipeline
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "50" }
spec:
  project: platform
  source:
    repoURL: 'https://github.com/2025-demo-01/data-pipeline'
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated: { prune: true, selfHeal: true }
