apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mesh
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "10" }
spec:
  project: platform
  source:
    repoURL: 'https://github.com/2025-demo-01/platform-mesh'
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
