apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-wide apps (mesh, policy, observability, dr)
  sourceRepos:
    - 'https://github.com/2025-demo-01/*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist: [{group: '*', kind: '*'}]
  namespaceResourceWhitelist: [{group: '*', kind: '*'}]
  orphanedResources: { warn: true }
