# platform-argocd/apps/data-pipeline.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/2025-demo-01/data-pipeline
    path: .
    targetRevision: v0.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
