# platform-argocd/apps/dr-failover.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dr-tests-and-failover
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/2025-demo-01/tests-and-dr
    path: dr
    targetRevision: v0.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dr-tests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
