apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://flagger.app
    chart: flagger
    targetRevision: 1.36.0
    helm:
      releaseName: flagger
      values: |
        meshProvider: istio
        metricsServer: "http://kube-prometheus-stack-prometheus.observability.svc:9090"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
