name: validate
on:
  pull_request:
    paths:
      - 'apps/**'
      - 'overlays/**'
      - 'bootstrap/**'
      - 'secrets/**'
      - '.github/workflows/**'
      - 'scripts/**'
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'overlays/**'
      - 'bootstrap/**'
      - 'secrets/**'
      - 'scripts/**'

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install kustomize + kubeconform + yq
        run: bash scripts/install-tools.sh

      - name: Kustomize build overlays/dev
        run: kustomize build overlays/dev | tee /dev/null

      - name: Kustomize build overlays/stg
        run: kustomize build overlays/stg | tee /dev/null

      - name: Kustomize build overlays/prod
        run: kustomize build overlays/prod | tee /dev/null

      - name: Kubeconform validate (dev/stg/prod)
        uses: yannh/kubeconform-action@v0.6.4
        with:
          kubernetes_version: v1.29.0
          schema_location: default
          files: |
            overlays/dev
            overlays/stg
            overlays/prod

      - name: Repo structure checks (waves, duplicates, secrets, latest)
        run: bash scripts/check_repo.sh

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length: { max: 160 }
              document-start: disable
